Voice Greeting: The WAV file plays on startup.
ASCII Art: Logo is centered and colorful.
Typing Effect: Adds polish to the user experience.
input Validation: Prevents empty queries.
Topic Handling: Good keyword matching for specific cybersecurity topics.
Color Coding: Blue for user (planned), green for bot – enhances readability.


